schema = 3

[mod]
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.4.0"
    hash = "sha256-75kRraVwYVjYLWZvuSlts4Iu28Eh3SpiF0GHc7vCYHI="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.55.8"
    hash = "sha256-8eDn4xgogWh96B7KUwOa6QoEtLW6QMc5LdsiwFtXTdE="
  [mod."github.com/codeclysm/extract/v3"]
    version = "v3.1.1"
    hash = "sha256-m97BzuMk+rlSfPUnYzWifqQBNNdrWZXhUlQwT2iY59A="
  [mod."github.com/containerd/typeurl/v2"]
    version = "v2.2.3"
    hash = "sha256-7hbXNe3LrJPgWbrvng8pYu9wgDp0IUvuCaq9wHhIrvs="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/distribution/reference"]
    version = "v0.6.0"
    hash = "sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/gkampitakis/ciinfo"]
    version = "v0.3.2"
    hash = "sha256-PQNWwVCZeNEPw0kMXmV2ymf4nqZKgT5EhlIDd1J8XeI="
  [mod."github.com/gkampitakis/go-diff"]
    version = "v1.3.2"
    hash = "sha256-Qh2lAShlRm571xMxhAOfRoaFYzrfHmmk7RQmSiJxPbo="
  [mod."github.com/gkampitakis/go-snaps"]
    version = "v0.5.14"
    hash = "sha256-NYaEoENrkIW38V65zjWi6Zb0uIZysvE6oMfYt0jN2nI="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.4.0"
    hash = "sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.18.0"
    hash = "sha256-7WH1WraWyGj7SvrOCnZkWdoGOVrQ9dkpj/zrckHq9+I="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/google/go-github/v63"]
    version = "v63.0.0"
    hash = "sha256-Yl33aGOXdGthRVp8vrM3At1NqvI/J3/LE82boXJ/rQs="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/h2non/filetype"]
    version = "v1.1.3"
    hash = "sha256-lSX/fSbT3MVlNK7d1U6Q/lBHtGXXAQ/HY4zW6Bppqhc="
  [mod."github.com/iancoleman/strcase"]
    version = "v0.3.0"
    hash = "sha256-lVOk4klrikSCUviR16qcyAr6eoIbniUSfsLFOE1ZLpk="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/juju/errors"]
    version = "v1.0.0"
    hash = "sha256-9uZ0wNf44ilzLsvXqOsmFUpNOBFAVadj6+ZH8+QMDMk="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.1"
    hash = "sha256-nkL7v2/C66brSfYRPN8FXLtUXN2I7VZ+Obvyc6be+GA="
  [mod."github.com/kr/pretty"]
    version = "v0.3.1"
    hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/maruel/natural"]
    version = "v1.1.1"
    hash = "sha256-eh5sNqcnxywonQ+56UAERpugr1jNxo7qJ+y09uOMChA="
  [mod."github.com/moby/buildkit"]
    version = "v0.26.0"
    hash = "sha256-NZr7vruMaEz/KW8XWgUx9GkBKGOjOqwV+WTenvq5bfU="
  [mod."github.com/moznion/go-optional"]
    version = "v0.13.0"
    hash = "sha256-dGH/c4jakHKILatmOyyl/qj4xJPSGJMqCE3UdUb5mr8="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/pan93412/envexpander/v3"]
    version = "v3.0.0"
    hash = "sha256-k/ASXsh/jVp6g65TJsocIxkjb16+LbIDMpNxA3G0P88="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/planetscale/vtprotobuf"]
    version = "v0.6.1-0.20240319094008-0393e58bdf10"
    hash = "sha256-L8dyNm+PCRDNADiIGKZqsPkCgB4xpLrosZjssrN+sUY="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.13.1"
    hash = "sha256-fD4n3XVDNHL7hfUXK9qi31LpBVzWnRK/7LNc3BmPtnU="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.12.0"
    hash = "sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws="
  [mod."github.com/samber/lo"]
    version = "v1.52.0"
    hash = "sha256-xgMsPJv3rydHH10NZU8wz/DhK2VbbR8ymivOg1ChTp0="
  [mod."github.com/samber/mo"]
    version = "v1.16.0"
    hash = "sha256-Rib8G2mBvU4r1qO8sRoHIIlWrTyUmE+ILdZc9orYsFM="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cast"]
    version = "v1.10.0"
    hash = "sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.1"
    hash = "sha256-OP6wdqk4dvBD8U5aicTkySHZ2s0LWnBo2TST2SmgcpM="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spf13/viper"]
    version = "v1.21.0"
    hash = "sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/tidwall/gjson"]
    version = "v1.18.0"
    hash = "sha256-CO6hqDu8Y58Po6A01e5iTpwiUBQ5khUZsw7czaJHw0I="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.1"
    hash = "sha256-S0uTDDGD8qr415Ut7QinyXljCp0TkL4zOIrlJ+9OMl8="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.5"
    hash = "sha256-OYGNolkmL7E1Qs2qrQ3IVpQp5gkcHNU/AB/z2O+Myps="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.15"
    hash = "sha256-L5KYLue5U14bxUuNyhZ6lIjbda6eCQsx1V6gToqfRdk="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250911091902-df9299821621"
    hash = "sha256-cSDirFex900mrckzB3fe18hW2Vk4/y4xKvlUWq3yoDA="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/text"]
    version = "v0.31.0"
    hash = "sha256-AT46RrSmV6+/d5FDhs9fPwYzmQ7WSo+YL9tPfhREwLw="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.10"
    hash = "sha256-gUrj1qSpjcpRKCBnrYlKMm+P0OSh7B/8EBREstwhD1w="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
